---
- name: Install Docker and docker compose on Ec2
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install docker
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - docker
          - python3
        update_cache: yes
        state: present
    - name: install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: run docker
      systemd:
        name: docker
        state: started
    - name: install docker python module
      pip:
        name: 
         - docker
         - docker-compose

 
- name: Add ec2 user to docker group
  hosts: docker_server
  become: yes
  tasks: 
  - name: docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnect to server
    meta: reset_connection
    

- name: Start docker
  hosts: docker_server
  vars_prompt:
    - name: password
      prompt: Enter password for Docker Hub 
  tasks:
    - name: Copy docker compose
      copy:
        src: /media/ahmedabed/Matrix/Labs/Ansible&Docker_project/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml 
    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: ahmedabed
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present 