---
- name: wait for ec2 to esablish 
  hosts: all
  gather_facts: False
  tasks:
    - name: ensure ssh to be open
      wait_for:
        port: 22
        delay: 10
        timout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'


- name: Install Docker and docker compose on Ec2
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install docker
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - docker
          - python3
        update_cache: yes
        state: present
    - name: install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: run docker
      systemd:
        name: docker
        state: started
    - name: install docker python module
      pip:
        name: 
         - docker
         - docker-compose

 
- name: Creat linux user 
  hosts: all
  become: yes
  tasks: 
    - name: Creat linux user
      user: 
        name: ahmed
        groups: adm,docker 

- name: Start docker
  hosts: all
  become: yes
  become_user: ahmed 
  vars_prompt:
    - name: password
      prompt: Enter password for Docker Hub 
  tasks:
    - name: Copy docker compose
      copy:
        src: /media/ahmedabed/Matrix/Labs/Ansible&Docker_project/docker-compose.yaml
        dest: /home/ahmed/docker-compose.yaml 
    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1
        username: ahmedabed
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ahmed
        state: present 